name: Deploy to WPMUdev

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to server
      uses: appleboy/scp-action@v0.1.5
      with:
        host: yourdocketonline.tempurl.host
        username: timcoe187
        port: 22
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "docket-onboarding"
        target: "site/public_html/wp-content/plugins"
        rm: true
